tls: 
  crt: |
    -----BEGIN CERTIFICATE-----
    MIIEdzCCAt+gAwIBAgIQcoA9zC4tkLQt/5H11SWGfDANBgkqhkiG9w0BAQsFADCB
    nTEeMBwGA1UEChMVbWtjZXJ0IGRldmVsb3BtZW50IENBMTkwNwYDVQQLDDBraWtv
    LmdvaW5oYXNAT1ZPLVgwTEZIQ1FSOUQubG9jYWwgKEtpa28gR29pbmhhcykxQDA+
    BgNVBAMMN21rY2VydCBraWtvLmdvaW5oYXNAT1ZPLVgwTEZIQ1FSOUQubG9jYWwg
    KEtpa28gR29pbmhhcykwHhcNMjMwOTAxMTcxMzI4WhcNMjUxMjAxMTgxMzI4WjBe
    MScwJQYDVQQKEx5ta2NlcnQgZGV2ZWxvcG1lbnQgY2VydGlmaWNhdGUxMzAxBgNV
    BAsMKmtpa28uZ29pbmhhc0BPVk8tWDBMRkhDUVI5RCAoS2lrbyBHb2luaGFzKTCC
    ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALGGGHNk4CO45eCkpFutDThP
    ay654zgovGAFkzKOaWAGPVh3/GfhrZdLkkSne4x2uX+8S1u8yvZZp5/TBcwsk0lB
    6FuHFdQSaxjgyDeB179HtozlSi6D4+y76AIJIEfAewIqxmY/0vpKFSjCK5Aj47UC
    hnpIHYfWVcmbdO5mVrSp8NHldDNTLsFQNeSfZ+h0VlHecZJp52M/sIzaNsXSHhNY
    7A7u0hQUt+aceGEkk8VHucy/fWBhc0XHBeM37L7zAqL2vv8/IlwQ4wrYjUzGXUzP
    8KzqVCygI+6PFhafwFtqbSCtgxN5iStiiPQFSGWj4a7j2mYChTt0ti48KM3cOFUC
    AwEAAaNxMG8wDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB8G
    A1UdIwQYMBaAFAvcnWPMDghvESWqioD4c9Mk8NNFMCcGA1UdEQQgMB6CDiouY2x1
    c3Rlci50ZXN0ggxjbHVzdGVyLnRlc3QwDQYJKoZIhvcNAQELBQADggGBAA4GZec8
    gbuZTM4225L6YgGtro7R+gAMxWHYgd1zh1XyPPtkrLNLjoy26PHDaVgDNtJD/TEH
    8nRbeU3f8JGQVJ/bWRYrHdPq6yxlp8C/jUx2ZgyIVL4yZdDJoxj4fPlrligUXqdF
    m8aPCIjXxmhnmXOsUEY7ttcNVT9yVEoKQ8iMAdbXWlVpRyu2LEfRt+P0ok26Hug4
    5y7vDECQsuQGTy/H6bLK+H3RLpmokruY6j8zE2eWnzbqMvP832HeBVIykYj1o0wf
    +G/ORKjxGTNIN39RD8M3ltH/kTGsZqSQFFbzRtgqBQN8phDIyII0COrTVgs5pRou
    VEJar1vYcqa4VhuKV+/tdavyUSHIY9zFysXHnfs4cV/92i/vNjp7uJIzyIxTPTu3
    CNh2gQRXye+Uf1jIf4tU5w0ESJwPSxFQHZukAQ7uus6gpOCjcitYBVRDowH8fYte
    isamTZyy7qTOJ938nhRR425/xTPQ2GCpt3896Rn4+AduRJLXqh+yZ1tIbg==
    -----END CERTIFICATE-----
  key: | 
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxhhhzZOAjuOXg
    pKRbrQ04T2suueM4KLxgBZMyjmlgBj1Yd/xn4a2XS5JEp3uMdrl/vEtbvMr2Waef
    0wXMLJNJQehbhxXUEmsY4Mg3gde/R7aM5Uoug+Psu+gCCSBHwHsCKsZmP9L6ShUo
    wiuQI+O1AoZ6SB2H1lXJm3TuZla0qfDR5XQzUy7BUDXkn2fodFZR3nGSaedjP7CM
    2jbF0h4TWOwO7tIUFLfmnHhhJJPFR7nMv31gYXNFxwXjN+y+8wKi9r7/PyJcEOMK
    2I1Mxl1Mz/Cs6lQsoCPujxYWn8Bbam0grYMTeYkrYoj0BUhlo+Gu49pmAoU7dLYu
    PCjN3DhVAgMBAAECggEAI4tX5fLytfRVgq80gW6a0QWFzmtFxX7SiN9U47CEBMf7
    DHWpwhr7qOlmtfxaznsPFTZcWFfqw3ycBXI5HPJn4ykhHwJjKn0tmGOZcxO6YQA4
    2ukl+z5JKqNNButQ3Uz61CpAY0SwN5ERv4FxO4EUHLAOwPkjgIk30BAiT4GKJs3y
    nQg3I2vHOn+XZBQ3WpXLYRA6AankhYUFN6YVUahOBm1mnxCW0y8fPwFnY3GKWxLw
    mxXL11AA4w+mgg4kVztCgVmfM8pf0jJsCGuAGFi735UppuE0zRuXHIbK6lRZHqQc
    R8ZwVLckAmR7h4z0/WB/klqfkNXsuH5XJ8QQqNcBgQKBgQDTrOpp2FXqlk4shpbB
    jh7F/JWq7IIn+s9pRKloyfXq0RTNCf0aOPq5z0Qy3xXpRpC4Zr7UJf9Ppx1bkVIA
    ucKqyvJXkIQjoCAcRptVXX68wjnRHSBXvxIk2TOpI1F9532zvf8W3KmWcB6rGn3B
    F0Uidu+27fQL4qVygPR1Rjf/5QKBgQDWsnIBHXp2uwJP10+OsSq45UUgWoYKuZsb
    N5UaJyOSNygz2Jh8M3q1+40OR8jdrNkxHhVwlzYVW3ZnSr69Xc65YMY8pAmz7LV2
    wyfdiC1JDkrfJDLLug/sbio79ds0dwWtkKuIhNwHnY/+PAChmRm0bs9OhFF6MnkK
    W1FKoXBvsQKBgQCsqXWk1PRwIB6wLzC1vYnYkco73CPnHK0m/vz5HxRbcCT5g1ZT
    l3rdKfZFULd8yzStVhH+1ufFP1mxIX60XNIvos+/IYDH1ouaxPVb0qHYss2ah5mk
    OZVBPXLoWojUnIlqnmZ/bYtfzSEXDMrbQHICROYQX1UchMnT9uBw8NApCQKBgAa4
    56DpT2BQUq41S6RoH7JSW2u76d6EGTss7lo3R4HYgEW/Tmb1Ja51BeGglcV7GAHV
    s04nLeZVSsvJJ1e+jC55vTtA15zumG/zhFgHX4OeEvIRrBV86eq5OFFQTWDDKUZZ
    9UT9A/apFE0di9eDd66SmaMXuYVd9zQ/z7fKfj7BAoGALJV2iMqDazjcxdGGvqck
    HqwD6w/ascAX85SJ4ysetYWz/U/bsM+L8Mbd/K6JRSaP8rsXhQBG7ueW/Q+qQqXM
    5Q+t1TJCvtnDDSxVL3MUz3akaE1C1IIKjQXnRyMZPDYpnfNIKWv126N6VP7yWFkx
    Rh4WJkVJ/4RVLII9RC5VtLw=
    -----END PRIVATE KEY-----
